export { default as Html } from "./html.png";
export { default as Css } from "./css.png";
export { default as Git } from "./git.png";
export { default as JS } from "./javascript.png";
export { default as Node } from "./node.png";
export { default as Py } from "./python.png";
export { default as ReactJS } from "./react-pro.png";
export { default as Tail } from "./tailwind.png";
export { default as VS } from "./vscode.png";
